In [14]:
import pandas as pd

import numpy as np

In [15]:
df = pd.read_csv("../Files/processed/clean_healthcare_readmissions.csv")

In [16]:
df.head(5)

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results,Patient_ID,Provider_ID,Record_ID,Encounter_ID,Length_of_Stay,Age_Group,Days_Since_Prior_Discharge,Is_Readmitted_30_Days
0,30,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal,PAT_1001,PRV_5001,1,ENC_10001,2,18-35,NaN,0
1,62,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive,PAT_1002,PRV_5002,2,ENC_10002,6,51-65,NaN,0
2,76,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal,PAT_1003,PRV_5003,3,ENC_10003,15,65+,NaN,0
3,28,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal,PAT_1004,PRV_5004,4,ENC_10004,30,18-35,NaN,0
4,43,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal,PAT_1005,PRV_5005,5,ENC_10005,20,36-50,NaN,0

Define the key identifier columns to place at the beginning

In [17]:
key_columns = ['Record_ID', 'Encounter_ID', 'Patient_ID', 'Provider_ID']

Getting the remaining columns in their existing order

In [18]:

other_columns = [col for col in df.columns if col not in key_columns]

Reorder DataFrame columns

In [19]:
df_reordered = df[key_columns + other_columns]

Saving the reordered DataFrame back to the CSV file

In [20]:
file_path = "../Files/processed/clean_healthcare_readmissions.csv"

In [21]:
df_reordered.to_csv(file_path, index=False)

In [22]:
df_reordered.head(5)

,Record_ID,Encounter_ID,Patient_ID,Provider_ID,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results,Length_of_Stay,Age_Group,Days_Since_Prior_Discharge,Is_Readmitted_30_Days
0,1,ENC_10001,PAT_1001,PRV_5001,30,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal,2,18-35,NaN,0
1,2,ENC_10002,PAT_1002,PRV_5002,62,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,51-65,NaN,0
2,3,ENC_10003,PAT_1003,PRV_5003,76,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal,15,65+,NaN,0
3,4,ENC_10004,PAT_1004,PRV_5004,28,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal,30,18-35,NaN,0
4,5,ENC_10005,PAT_1005,PRV_5005,43,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal,20,36-50,NaN,0

In [23]:
df_reordered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Record_ID                   55500 non-null  int64
 1   Encounter_ID                55500 non-null  object
 2   Patient_ID                  55500 non-null  object
 3   Provider_ID                 55500 non-null  object
 4   Age                         55500 non-null  int64
 5   Gender                      55500 non-null  object
 6   Blood Type                  55500 non-null  object
 7   Medical Condition           55500 non-null  object
 8   Date of Admission           55500 non-null  object
 9   Hospital                    55500 non-null  object
 10  Insurance Provider          55500 non-null  object
 11  Billing Amount              55500 non-null  float64
 12  Admission Type              55500 non-null  object
 13  Discharge Date              55500 non-null  object
 14  Medication                  55500 non-null  object
 15  Test Results                55500 non-null  object
 16  Length_of_Stay              55500 non-null  int64
 17  Age_Group                   55500 non-null  object
 18  Days_Since_Prior_Discharge  15265 non-null  float64
 19  Is_Readmitted_30_Days       55500 non-null  int64
dtypes: float64(2), int64(4), object(14)
memory usage: 8.5+ MB